apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertsystem
  labels: 
    app: alertsystem
spec:
  replicas: 1
  selector:
    matchlabels:
      app: alertsystem
  template:
    metadata:
      labels:
        app: alertsystem
    spec:
      containers:
        - image: pulvirenti300666/dsbd_repo/alertsystemimage
          name: alertsystem
          ports:
            - containerPort: 50051
      restartPolicy: Always
apiVersion: v1
kind: Service
metadata:
  name: alertsystem
  labels:
    run: alertsystem
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    run: alertsystem

