apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: datacollector
  name: datacollector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datacollector
  template:
    metadata:
      labels:
        app: datacollector
    spec:
      containers:
        - image: datacollectorimage
          name: datacollector
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: datacollector
spec:
  selector:
    app: datacollector
  ports:
    - name: datacollector-port  
      protocol: TCP
      port: 8002         # Porta esposta dal servizio
      targetPort: 8002   # Porta del container gRPC
  type: ClusterIP-port
      protocol: TCP

