# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import user_management_pb2 as user__management__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in user_management_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterUser = channel.unary_unary(
                '/UserManagement/RegisterUser',
                request_serializer=user__management__pb2.RegisterUserRequest.SerializeToString,
                response_deserializer=user__management__pb2.UserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/UserManagement/UpdateUser',
                request_serializer=user__management__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=user__management__pb2.UserResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/UserManagement/DeleteUser',
                request_serializer=user__management__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=user__management__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.GetLatestStockValue = channel.unary_unary(
                '/UserManagement/GetLatestStockValue',
                request_serializer=user__management__pb2.GetLatestStockValueRequest.SerializeToString,
                response_deserializer=user__management__pb2.StockValueResponse.FromString,
                _registered_method=True)
        self.GetAverageStockValue = channel.unary_unary(
                '/UserManagement/GetAverageStockValue',
                request_serializer=user__management__pb2.GetAverageStockValueRequest.SerializeToString,
                response_deserializer=user__management__pb2.AverageValueResponse.FromString,
                _registered_method=True)


class UserManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterUser(self, request, context):
        """Gestione Utenti
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestStockValue(self, request, context):
        """Recupero Dati
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAverageStockValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=user__management__pb2.RegisterUserRequest.FromString,
                    response_serializer=user__management__pb2.UserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=user__management__pb2.UpdateUserRequest.FromString,
                    response_serializer=user__management__pb2.UserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=user__management__pb2.DeleteUserRequest.FromString,
                    response_serializer=user__management__pb2.DeleteResponse.SerializeToString,
            ),
            'GetLatestStockValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestStockValue,
                    request_deserializer=user__management__pb2.GetLatestStockValueRequest.FromString,
                    response_serializer=user__management__pb2.StockValueResponse.SerializeToString,
            ),
            'GetAverageStockValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAverageStockValue,
                    request_deserializer=user__management__pb2.GetAverageStockValueRequest.FromString,
                    response_serializer=user__management__pb2.AverageValueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UserManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserManagement/RegisterUser',
            user__management__pb2.RegisterUserRequest.SerializeToString,
            user__management__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserManagement/UpdateUser',
            user__management__pb2.UpdateUserRequest.SerializeToString,
            user__management__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserManagement/DeleteUser',
            user__management__pb2.DeleteUserRequest.SerializeToString,
            user__management__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestStockValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserManagement/GetLatestStockValue',
            user__management__pb2.GetLatestStockValueRequest.SerializeToString,
            user__management__pb2.StockValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAverageStockValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserManagement/GetAverageStockValue',
            user__management__pb2.GetAverageStockValueRequest.SerializeToString,
            user__management__pb2.AverageValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
