# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_management.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'user_management.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15user_management.proto\"m\n\x13RegisterUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\x11\n\thighvalue\x18\x03 \x01(\x01\x12\x10\n\x08lowvalue\x18\x04 \x01(\x01\x12\x12\n\ntelegramid\x18\x05 \x01(\x03\"k\n\x11UpdateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\x11\n\thighvalue\x18\x03 \x01(\x01\x12\x10\n\x08lowvalue\x18\x04 \x01(\x01\x12\x12\n\ntelegramid\x18\x05 \x01(\x03\"\"\n\x11\x44\x65leteUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"+\n\x1aGetLatestStockValueRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\";\n\x1bGetAverageStockValueRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"0\n\x0cUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"F\n\x12StockValueResponse\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"\'\n\x14\x41verageValueResponse\x12\x0f\n\x07\x61verage\x18\x01 \x01(\x01\x32\xbf\x02\n\x0eUserManagement\x12\x33\n\x0cRegisterUser\x12\x14.RegisterUserRequest\x1a\r.UserResponse\x12/\n\nUpdateUser\x12\x12.UpdateUserRequest\x1a\r.UserResponse\x12\x31\n\nDeleteUser\x12\x12.DeleteUserRequest\x1a\x0f.DeleteResponse\x12G\n\x13GetLatestStockValue\x12\x1b.GetLatestStockValueRequest\x1a\x13.StockValueResponse\x12K\n\x14GetAverageStockValue\x12\x1c.GetAverageStockValueRequest\x1a\x15.AverageValueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_management_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERUSERREQUEST']._serialized_start=25
  _globals['_REGISTERUSERREQUEST']._serialized_end=134
  _globals['_UPDATEUSERREQUEST']._serialized_start=136
  _globals['_UPDATEUSERREQUEST']._serialized_end=243
  _globals['_DELETEUSERREQUEST']._serialized_start=245
  _globals['_DELETEUSERREQUEST']._serialized_end=279
  _globals['_GETLATESTSTOCKVALUEREQUEST']._serialized_start=281
  _globals['_GETLATESTSTOCKVALUEREQUEST']._serialized_end=324
  _globals['_GETAVERAGESTOCKVALUEREQUEST']._serialized_start=326
  _globals['_GETAVERAGESTOCKVALUEREQUEST']._serialized_end=385
  _globals['_USERRESPONSE']._serialized_start=387
  _globals['_USERRESPONSE']._serialized_end=435
  _globals['_DELETERESPONSE']._serialized_start=437
  _globals['_DELETERESPONSE']._serialized_end=487
  _globals['_STOCKVALUERESPONSE']._serialized_start=489
  _globals['_STOCKVALUERESPONSE']._serialized_end=559
  _globals['_AVERAGEVALUERESPONSE']._serialized_start=561
  _globals['_AVERAGEVALUERESPONSE']._serialized_end=600
  _globals['_USERMANAGEMENT']._serialized_start=603
  _globals['_USERMANAGEMENT']._serialized_end=922
# @@protoc_insertion_point(module_scope)
